envVarGroups:
  - name: playto-pay-backend-env
    envVars:
      - key: DJANGO_SECRET_KEY
        generateValue: true
      - key: DJANGO_DEBUG
        value: false
      - key: DJANGO_ALLOWED_HOSTS
        value: .onrender.com

services:
  - type: keyvalue
    name: playto-pay-redis
    ipAllowList: []

  - type: web
    name: playto-pay-api
    runtime: python
    rootDir: backend
    buildCommand: pip install -r requirements.txt
    preDeployCommand: python manage.py migrate
    startCommand: gunicorn config.wsgi:application --bind 0.0.0.0:$PORT
    healthCheckPath: /health/
    envVars:
      - fromGroup: playto-pay-backend-env
      - key: DATABASE_URL
        fromDatabase:
          name: playto-pay-db
          property: connectionString
      - key: CELERY_BROKER_URL
        fromService:
          type: keyvalue
          name: playto-pay-redis
          property: connectionString
      - key: CELERY_RESULT_BACKEND
        fromService:
          type: keyvalue
          name: playto-pay-redis
          property: connectionString

  - type: worker
    name: playto-pay-worker
    runtime: python
    rootDir: backend
    buildCommand: pip install -r requirements.txt
    startCommand: celery -A config worker -l info
    envVars:
      - fromGroup: playto-pay-backend-env
      - key: DATABASE_URL
        fromDatabase:
          name: playto-pay-db
          property: connectionString
      - key: CELERY_BROKER_URL
        fromService:
          type: keyvalue
          name: playto-pay-redis
          property: connectionString
      - key: CELERY_RESULT_BACKEND
        fromService:
          type: keyvalue
          name: playto-pay-redis
          property: connectionString

  - type: worker
    name: playto-pay-beat
    runtime: python
    rootDir: backend
    buildCommand: pip install -r requirements.txt
    startCommand: celery -A config beat -l info
    envVars:
      - fromGroup: playto-pay-backend-env
      - key: DATABASE_URL
        fromDatabase:
          name: playto-pay-db
          property: connectionString
      - key: CELERY_BROKER_URL
        fromService:
          type: keyvalue
          name: playto-pay-redis
          property: connectionString
      - key: CELERY_RESULT_BACKEND
        fromService:
          type: keyvalue
          name: playto-pay-redis
          property: connectionString

  - type: web
    name: playto-pay-ui
    runtime: static
    rootDir: frontend
    buildCommand: npm install && npm run build
    staticPublishPath: dist
    envVars:
      - key: VITE_API_BASE_URL
        sync: false

databases:
  - name: playto-pay-db
